languageCode = "zh-cn"
title = "SunnyCloudYang"
baseURL = "https://sunnycloudyang.github.io/"
theme = "massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
[params.posts]
    folderName = "post"
    pageSize = "6"
    featuredPost = true
    paginationPages = 2
    showFirstLast = true
 
[languages]
[languages.zh]
  languageName = "简体中文"
[languages.en]
  languageName = "English"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"

